<?php

use PHPUnit\Framework\TestCase;
use Workflow\Context;

class Compiler extends TestCase
{
    private \Psr\Container\ContainerInterface $di;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $compiler = new Workflow\Compiler\Compiler(
            __DIR__ . '/../var/workflow',
            __DIR__ . '/config',
        );

        $compiler->compile(new \Workflow\Compiler\ConfigurationInterpreter());
        $definitions = include $compiler->getDefinitionFilename();
        $builder = new \DI\ContainerBuilder();

        $builder->addDefinitions($definitions);
        $this->di = $builder->build();

    }

    public function test_build_from_yaml(): void
    {
        /** @var \Workflow\Workflow $workflow */
        $workflow = $this->di->get('workflow-example');
        $context = new Context();
        $context->assign('a', 1);
        $result = $workflow->execute($context);

        self::assertEquals('String with value = 2', $result);


        $context = new Context();
        $context->assign('a', 3);
        $result = $workflow->execute($context);

        self::assertEquals('Value is 3', $result);

    }

    public function test_with_call_action(): void
    {

        $workflow = $this->di->get('custom-action-workflow');

        $this->di->set('Increment', new class {
            public function __invoke(int $value, int $incrementBy): int
            {
                return $value + $incrementBy;
            }
        });
        $context = new Context();
        $context->assign('a', 1);
        $result = $workflow->execute($context);

        self::assertTrue($result);
    }


}